const path = require('path')
const MedianFinder = require('./')

describe(path.basename(__dirname), () => {
  test('Case #0', () => {
    const finder = new MedianFinder()
    finder.addNum(1)
    finder.addNum(2)
    expect(finder.findMedian()).toBe(1.5)
    finder.addNum(3)
    expect(finder.findMedian()).toBe(2)
  })

  test('Case #1', () => {
    const finder = new MedianFinder()
    finder.addNum(6)
    expect(finder.findMedian()).toBe(6)
    finder.addNum(10)
    expect(finder.findMedian()).toBe(8)
    finder.addNum(2)
    expect(finder.findMedian()).toBe(6)
    finder.addNum(6)
    expect(finder.findMedian()).toBe(6)
    finder.addNum(5)
    expect(finder.findMedian()).toBe(6)
    finder.addNum(0)
    expect(finder.findMedian()).toBe(5.5)
    finder.addNum(6)
    expect(finder.findMedian()).toBe(6)
    finder.addNum(3)
    expect(finder.findMedian()).toBe(5.5)
    finder.addNum(1)
    expect(finder.findMedian()).toBe(5)
    finder.addNum(0)
    expect(finder.findMedian()).toBe(4)
    finder.addNum(0)
    expect(finder.findMedian()).toBe(3)
  })
})
